server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;
    client_max_body_size 20m;

    # Service worker : jamais en cache
    location = /ngsw-worker.js {
        add_header Cache-Control "no-cache";
    }

    location = /ngsw.json {
        add_header Cache-Control "no-cache";
    }

    location = /index.html {
        add_header Cache-Control "no-cache";
    }

    # Fichiers hashés : cache long
    location ~* \.(?:js|css|woff2?|ttf|svg|png|jpg|jpeg|gif|ico|webp)$ {
        expires 1y;
        add_header Cache-Control "public, immutable";
        try_files $uri =404;
    }

    # SPA Angular
    location / {
        try_files $uri $uri/ /index.html;
    }
}